server:
  port: 8080

mybatis:
  mapper-locations: classpath*:mapper/*.xml

spring:
  datasource:
    username: 
    password: 
    url: jdbc:mysql://:3306/trade?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
